### ISSUE TITLE
Add picture of mundo

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/vim-mundo#1]
Need to crop it

![](http://ddragon.leagueoflegends.com/cdn/img/champion/splash/DrMundo_0.jpg)

**Comment by wsdjeg** [comment]
wow nice

**Comment by simnalamburt** [comment]
The name of this repository, `mundo` is indeed a hommage of the game character [Dr. Mundo](http://leagueoflegends.wikia.com/wiki/Dr._Mundo) of [League of Legends](https://www.leagueoflegends.com/). When I first forked the [`gundo.vim`](https://bitbucket.org/sjl/gundo.vim) into `vim-mundo`, I was enthusiastic player of that game. But three years have passed and now I totally lost interests of that game.

Since not only the usage of Dr. Mundo's illustration may cause copyright issue, but also it's not funny for both me and readers. I'm closing this issue.
