### ISSUE TITLE
trying to show undo tree of a popup window generates errors

### ISSUE THREAD

**Issue by cridemichel** [simnalamburt/vim-mundo#103]
Dear Developer,
if mundo tree is shown and I open a preview window (e.g. by fzf vim plugin), an error
occurs since vim-mundo tries to show the undo tree of the preview window.
I created a pull request for preventing vim-mund to show the undo tree of a preview window, thus suppressing
the error messages,

best Cristiano

**Comment by simnalamburt** [comment]
Closed by https://github.com/simnalamburt/vim-mundo/pull/102

Thanks for you contribution! ✨👍✨
