### ISSUE TITLE
'r' and 'd' do same thing 

### ISSUE THREAD

**Issue by cridemichel** [simnalamburt/vim-mundo#105]
Dear Developer,
by pressing in the "__Mundo__" buffer the keys 'r' or 'd' 
one obtains in both cases a vert diffpatch of undo and current buffer.
I have just created a pull request to make mundo do what is reported in the help
about pressing 'r',  i.e. showing in the preview window the differences with the
previous state,

best Cristiano

**Comment by simnalamburt** [comment]
Closed by https://github.com/simnalamburt/vim-mundo/pull/104
