### ISSUE TITLE
Error when pressing ? if g:mundo_help is enabled

### ISSUE THREAD

**Issue by arp242** [simnalamburt/vim-mundo#114]
When you set `g:mundo_help` pressing `?` errors out:

```
:let g:mundo_help=1
:MundoToggle
:normal ?
Error detected while processing function <SNR>60_MundoPython[1]..function <SNR>60_MundoPython:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/martin/.cache/vim/pack/plugins/start/vim-mundo/autoload/mundo.py", line 460, in MundoToggleHelp
    vim.command(
vim.error: Vim(call):E475: Invalid argument: -8
```

It does hide the help though, and subsequent `?` presses work as expected.

vim 8.2.3156 with Python 3.9.6 on Linux.

**Comment by arp242** [comment]
Somewhat related issue: by default mundo doesn't allow you to scroll in the "header", but if you set both:

    let g:mundo_help = 1
    let g:mundo_header = 0

Then mundo won't allow you to scroll all the way up.

**Comment by simnalamburt** [comment]
Cannot reproduce this issue, considering it as fixed.
