### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by mrHola21** [simnalamburt/vim-mundo#117]
I am on Manjaro Linux and have python3 installed and its in the path (when `python3` typed in the terminal the python shell opens). 

when I open neovim (latest version) and type `:MundoShow` it says that I don't have a supported python version.

python3 version = 3.9.7
python2 version = 2.7.18
kernel version = 5.4.150-1-MANJARO
plugin manager = Vim-Plug

and I have git setup if that helps

**Comment by simnalamburt** [comment]
AFAIK neovim requites pynvim package to be installed to use python extensions. Do you have pynvim?

**Comment by mrHola21** [comment]
Yes install pynvim solved the error but don't you think you should include it in  the readme . btw this one of the best plugins :)

**Comment by simnalamburt** [comment]
@mrHola21 Good point. I've updated it!

<img width="418" alt="image" src="https://user-images.githubusercontent.com/4435445/140911812-f68d24ef-8bb4-440a-8cbb-bcaf12a86332.png">
