### ISSUE TITLE
Weird Window Focus

### ISSUE THREAD

**Issue by axieax** [simnalamburt/vim-mundo#118]
Hi, I've just switched from UndoTree to vim-mundo and am encountering an annoying issue. After activating the Mundo menu, it seems that none of the default keybindings nor auto_preview work, requiring me to switch to another window and back before these features work, as demonstrated in the video below. Not sure why this happens and whether or not this is due to [my configs](https://github.com/axieax/dotconfig/blob/main/nvim/lua/general.lua) somewhere. Your help would be much appreciated! 

p.s. I am on Neovim version 0.5.1

https://user-images.githubusercontent.com/62098008/143536764-25a9ae6e-595d-47c2-84a7-5e6a476a3d3d.mp4

**Comment by simnalamburt** [comment]
I'm using Neovim v0.6.0 and having trouble with reproducing this issue. I'll try your vimrc soon.

**Comment by axieax** [comment]
Not sure what changed but I'm on v0.6 now and it works fine :)
