### ISSUE TITLE
Selecting an entry in the history tree doesn't always 'take'.

### ISSUE THREAD

**Issue by dsummersl** [simnalamburt/vim-mundo#12]
I notice sometimes that when I select an issue in my history tree, the main file doesn't update.

**Comment by Stebalien** [comment]
Same problem here.

**Comment by wreed4** [comment]
I agree.  Was just going to file an issue about this.  I dont' know how to fix it, but sometimes exiting and entering again makes it work again.  I've mostly been using neovim, but this also happens in regular vim.

**Comment by dsummersl** [comment]
Thanks for the feedback @wreed4 - I think https://github.com/simnalamburt/vim-mundo/pull/13 is gonna fix this. In the final bit of testing.

**Comment by dsummersl** [comment]
Issue #13 has gone out - I haven't seen this problem since. If someone does please let me know.

**Comment by dsummersl** [comment]
Closing, I haven't seen this issue.
