### ISSUE TITLE
No module named 'neovim'

### ISSUE THREAD

**Issue by asaning** [simnalamburt/vim-mundo#128]
![image](https://user-images.githubusercontent.com/99789353/230768173-6a870145-edc7-44f5-a2cf-008964e61b43.png)

when i try to use `MundoToggle` to show tne undo list,it breaks.

**Comment by dsummersl** [comment]
Hi @asaning  - can you send me your output for `:version`? My first guess is that you're using Vim, and we have a regression.

**Comment by mcauley-penney** [comment]
I am currently experiencing this problem as well, on the current neovim `HEAD`.

```
:version
NVIM v0.10.0-dev-1413+g684e93054
Build type: Release
LuaJIT 2.1.1697887905
Run ":verbose version" for more info
```

**Comment by dsummersl** [comment]
Have you installed the python neovim package? This plugin requires the pynvim python provider (`pip install pynvim`)

**Comment by mcauley-penney** [comment]
That was the problem for me, thank you! I had it installed before Arch/pip started managing Python packages via the package manager, so I assumed I still had it in working order. Something may have been lost in the process.
