### ISSUE TITLE
Can't run under vim compiled with python support version 3.12

### ISSUE THREAD

**Issue by jjh2811** [simnalamburt/vim-mundo#129]
Hi.
After using vim complied with python 3.12, 
vim-mundo couldn't run saying the following error. (You can't reproduce this error if you use vim compiled with python <3.12.)

```Error detected while processing function mundo#MundoToggle[1]..<SNR>156_MundoToggle[4]..<SNR>156_MundoOpen:
line   14:
/home/ubuntu/.vim/plugged/vim-mundo/autoload/mundo.py:197: SyntaxWarning: invalid escape sequence '\['
  matches = re.match('^[^\[]* \[([0-9]+)\] .*$', target_line)
```
and I found out this error could be fixed after modifying the line of mundo.py.
line 197 of mundo.py(Edit):
`matches = re.match(r'^[^\[]* \[([0-9]+)\] .*$', target_line)`

**Comment by dsummersl** [comment]
Hi @jjh2811 thank you! I'll make a note to get this fixed shortly!
