### ISSUE TITLE
Rebrand plugin

### ISSUE THREAD

**Issue by dsummersl** [simnalamburt/vim-mundo#15]
Change `gundo` to `mundo` named variables? Maybe not - that would require those upgrading from the old plugin to rename their variables...

But - rename `gundo.txt` to `mundo.txt`, and make the changelog 3.X the official 3.0 release.

**Comment by simnalamburt** [comment]
Absolutely agree with this. It's been half year since I forked this and stil sjl is sleeping (while he is [stil alive](https://bitbucket.org/sjl/dotfiles/commits/all)).

I'm 100% agree with rebranding this plugin so that we can publicize this not hidden by original [Gundo](http://sjl.bitbucket.org/gundo.vim/). But about variables, I don't want to break their experience if there's any good possible way. Here's my suggestion:

1. For internal names, rename all `gundo` &rarr; `mundo`
2. For config variables, support both `gundo` and `mundo` **for a while** (this ain't gonna live forever).<br>
If both exists, `mundo` precedes `gundo`
3. Remove all `gundo`s from all documentations, so people will slowly forget `gundo`.
4. Make another documentation for `mundo` so that we can expose it to Google.

**Comment by wsdjeg** [comment]
@dsummersl @simnalamburt I am start to do this now ,a better way support both mundo and gundo first,

**Comment by simnalamburt** [comment]
@wsdjeg :+1:

**Comment by wsdjeg** [comment]
finished

**Comment by simnalamburt** [comment]
Thank you @wsdjeg, pretty much works just have done by #25, now left things to do is updating README and documentations

**Comment by wsdjeg** [comment]
@simnalamburt I Just fix the test and change the buf Name from _Gundo_ to _Mundo_

**Comment by simnalamburt** [comment]
@wsdjeg :+1:

**Comment by wsdjeg** [comment]
thanks ,I really love this plugin :dancer:

**Comment by dsummersl** [comment]
@wsdjeg this looks great, thank you so much!

**Comment by wsdjeg** [comment]
@dsummersl should we rename the script file name , also I think  if the licenses is ok, we can remove the fork, and let more people seach for this plugin ,then no result for this plugin
https://github.com/search?utf8=%E2%9C%93&q=mundo.vim
also wen can not search code from this repo
**Sorry, forked repositories are not currently searchable**

**Comment by simnalamburt** [comment]
WTF

@wsdjeg Acknowledged, I'll take care of this problem seriously

**Comment by wsdjeg** [comment]
that means we can not remove the fork flag?

**Comment by simnalamburt** [comment]
We maybe should recreate this repo

**Comment by wsdjeg** [comment]
Do you kown,how to got it ,also I can help you ,

**Comment by wsdjeg** [comment]
you shoul deal with Redirect manual,because many people now using Plugin 'simnalamburt/vim-mundo'

**Comment by simnalamburt** [comment]
That's right. GitHub does track down changing project's name so currently this plugin is downloadable with `simnalamburt/gundo.vim`, but I haven't tested it with transferring ownership to organization. Let me try it with dummy org

**Comment by wsdjeg** [comment]
###please do not do like this

**Comment by wsdjeg** [comment]
### here is the step
1. clone this repo to you pc local
2. delete simnalamburt/vim-mundo 
3. create a new repo named `vim-nundo` yourself
3. create a new org or not ,I think it is better use Mundo.vim as the org name
4. thansfe the ownership of the new repo simnalamburt/vim-mundo to the org

**Comment by simnalamburt** [comment]
Thanks @wsdjeg I've been busy for a while, let me handle this work this weekend. Thank you for your contributions again.

**Comment by wsdjeg** [comment]
you are welcome

**Comment by simnalamburt** [comment]
I just sent a reqeust to extract `vim-mundo` into its own fork network (means, please remove that 'forked from ~~~' sign).

###### Reference
- http://stackoverflow.com/a/29326840

**Comment by wsdjeg** [comment]
how long will this take.I found ctrlp.vim still has the fork mark.

**Comment by simnalamburt** [comment]
@wsdjeg Don't know yet. I didn't wanted to lose those issues and pull requests, so let's wait a few day and recreate this repo if github doesn't reply.

**Comment by wsdjeg** [comment]
yeah,I also didn't wanted to lose those,and maybe there is no need remove the fork mark.

**Comment by simnalamburt** [comment]
Fork mark removed

**Comment by wsdjeg** [comment]
oh,greate

**Comment by wsdjeg** [comment]
How about update the project website?

**Comment by dsummersl** [comment]
Yes I love that idea - I’d love for us to have some updated screenshots or maybe a screencast too!

**Comment by dsummersl** [comment]
@wsdjeg I guess we better update our project website finally, then. Happy new years, thanks for including our project!

**Comment by wsdjeg** [comment]
yeah. happy new years too.

**Comment by simnalamburt** [comment]
Currently I'm updating the github pages

**Comment by simnalamburt** [comment]
It took one and a half year to update the online documentation 😅 Thanks to both @dsummersl and @wsdjeg for contributing this project and toleration my lazyness

**Comment by simnalamburt** [comment]
Now vim-mundo is the third search result of "vim undo tree" in Google. Greate works everyone!

<img width="1239" alt="2017-10-26 11 22 19" src="https://user-images.githubusercontent.com/4435445/32032772-dfc2d42e-ba43-11e7-8ff9-fc34c8ed6eb2.png">

**Comment by simnalamburt** [comment]
Closing in favor of #82
