### ISSUE TITLE
Gundo requires vim to be compiled with python 2.4+ (using neovim)

### ISSUE THREAD

**Issue by benbarbour** [simnalamburt/vim-mundo#18]
I'm using the latest neovim (at the time of writing I *just* got the source and built it) and I get the titular error when trying to invoke Gundo.

**Comment by simnalamburt** [comment]
Acknowledged, let me try it.

**Comment by roboll** [comment]
Seeing this as well, any idea if this is _actually_ supporting neovim?

**Comment by benbarbour** [comment]
IIRC it was working for a while and then I updated my plugins. I haven't gone back and tried to figure out a working version yet.

**Comment by simnalamburt** [comment]
I just tested it with [`neovim-git`](https://aur.archlinux.org/packages/neovim-git/) AUR on the Archlinux and found no problem.

* OS: Archlinux
* Neovim: Compiled with https://github.com/neovim/neovim/commit/db7b9700
* Python: `Python 2.7.10` was installed

@benbarbour, can you tell me your environment which produced the titular error? Currently I have problem with reproducing the error. :cry:

**Comment by benbarbour** [comment]
Hurm... I just tried to reproduce it and I can't. I have updated neovim in the meantime, so perhaps that's all that's needed. For the record, I've currently built off of neovim's 544ec08102b7a763a2a26bfea1310b545f498850 commit.

**Comment by simnalamburt** [comment]
Alright, closing the issue. @benbarbour please mention me if this issue occurs again :+1:

**Comment by A-deLuna** [comment]
@simnalamburt I'm running into this issue with [neovim 0.1.0-1](https://www.archlinux.org/packages/community/x86_64/neovim/) from the official Arch repos

**Comment by dsummersl** [comment]
What do you see if you type `echo has('python')`; have you installed the neovim python package (`pip install neovim`)?

**Comment by A-deLuna** [comment]
thanks @dsummersl!
my problem was that I had not installed python2-neovim

**Comment by simnalamburt** [comment]
Great!

**Comment by jesusabarca** [comment]
For OS X users, install python 2 integration package with:

`sudo pip2 install --upgrade neovim`

Source https://neovim.io/doc/user/provider.html
