### ISSUE TITLE
vim-mundo broken with Python 3.5

### ISSUE THREAD

**Issue by phongvcao** [simnalamburt/vim-mundo#21]
I recently upgraded my Python version to 3.5 on Arch Linux. Here is what I got after opening `vim-mundo`:

Error detected while processing function gundo#GundoToggle[1]..<SNR>318_GundoToggle[11]..<SNR>318_GundoOpen[32]..<SNR>318_GundoPython:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/phongvcao/.vim/bundle/vim-mundo/autoload/gundo.py", line 166, in GundoRenderPreview
    util._output_preview_text(nodesData.preview_diff(node_before, node_after))
  File "/home/phongvcao/.vim/bundle/vim-mundo/autoload/mundo/node.py", line 188, in preview_diff
    before_time, after_time))
  File "/usr/lib/python3.5/difflib.py", line 1177, in unified_diff
    _check_types(a, b, fromfile, tofile, fromfiledate, tofiledate, lineterm)
  File "/usr/lib/python3.5/difflib.py", line 1312, in _check_types
    raise TypeError('all arguments must be str, not: %r' % (arg,))
TypeError: all arguments must be str, not: 1

Here are the version information:
vim-mundo: Latest from Github
Python: v3.5.0
OS: 4.2.5-1-ARCH
Vim: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 28 2015 08:50:05) - Included patches: 1-884

Hope there will be a fix soon.

**Comment by dsummersl** [comment]
Hi @phongvcao I'm sorry I haven't gotten to this yes - I've had some trouble reproducing on the exact platform. I'll give it another shot shortly...

**Comment by phongvcao** [comment]
@dsummersl make sure you install vim-python3 & Python 3.5. Also, I use tmux and I don't know if this problem is somehow related to my tmux, even though I doubt it... I will test vim-mundo again without tmux later tonight.

**Comment by phongvcao** [comment]
@dsummersl okay so this issue is independent of tmux... The error occurs when I tried to scroll through nodes of the vim-mundo's history tree...

**Comment by simnalamburt** [comment]
Acknowledged, let me try it shortly
