### ISSUE TITLE
Merge reasonable pull requests as much as possible

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/vim-mundo#3]
- [x] https://github.com/sjl/gundo.vim/pull/30
- [x] https://github.com/sjl/gundo.vim/pull/29
- [x] https://github.com/sjl/gundo.vim/pull/28
- [x] https://github.com/sjl/gundo.vim/pull/27
- [x] [dsummersl/gundo.vim](https://github.com/dsummersl/gundo.vim)

**Comment by dsummersl** [comment]
Sounds good @simnalamburt I'll get my project up to date with yours and submit a PR soonish.

**Comment by simnalamburt** [comment]
Thank you very much!

**Comment by dsummersl** [comment]
I like slj#27 (plus they include doc updates in the PR, which is nice :)). Sound good?

**Comment by simnalamburt** [comment]
Sounds not bad. Looks like we need some rebase process.

**Comment by dsummersl** [comment]
For...j3master to rebase against our fork? (sorry little confused about what you meant).

In the meantime I've added j3master's fork as a remote and merged it into a new branch to make this PR:

https://github.com/simnalamburt/vim-mundo/pull/7

Could you take a peak when you get a chance - I played with a couple combinations of settings and it appears to work as advertized. I *do* like it even.

**Comment by simnalamburt** [comment]
Sorry for confusion, you did what I wanted
