### ISSUE TITLE
Error when opening help (i.e. ?)

### ISSUE THREAD

**Issue by starcraftman** [simnalamburt/vim-mundo#30]
To reproduce: Open the MundoToggle, then simply push `?`.

Error Recieved:
```viml
Error detected while processing function <SNR>168_MundoPython:
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/starcraftman/.shell/dot/files/vim/plugged/vim-mundo/autoload/mundo.py", line 402, in 
MundoToggleHelp
    vim.command("call cursor(getline('.') - %d)" % (len(INLINE_HELP.split('\n')) - 2))
vim.error: Vim(call):E474: Invalid argument
E171: Missing :endif
```

**Comment by dsummersl** [comment]
Hi @starcraftman - Pressing ? works for me - what version of vim/neovim are you using? (`:version`). Also...what version of python?

**Comment by starcraftman** [comment]
@dsummersl Python 2.7.10, Vim patches 1-1261, compiled myself with +python.

**Comment by dsummersl** [comment]
@starcraftman check out @djjcast 's fix out and let me know if it works for you. Thanks!

**Comment by starcraftman** [comment]
@dsummersl Works fine now, thanks for fixing it.
