### ISSUE TITLE
Incomplete Rename

### ISSUE THREAD

**Issue by starcraftman** [simnalamburt/vim-mundo#31]
Hi, it seems during the rename you might have forgot at least two files. The first rename caused an rsync I was running on my plugged dir to crash, since it pointed to a non-existent file.
- `tests/vim_test/plugin/gundo.vim` ->  `tests/vim_test/plugin/mundo.vim`, link should be remade as it still points to gundo.vim
- `tests/vim_test/plugin/gundo_test_utils.vim` -> `tests/vim_test/plugin/mundo_test_utils.vim`

More generally, I might suggest simply having multiple `set rtps` in your vimrc_test instead of trying to link everything into one plugin setup. You could for instance, use a directory under `/tmp` as a staging area for test depenencies/vimrc, then simply make sure the rtp is correct. Requires generating the vimrc for test machine.

If you want an example, [see here](https://github.com/starcraftman/plug-search/blob/master/tests/run.sh). Uses vader instead of UT.

**Comment by dsummersl** [comment]
Hi @starcraft I'll get that link fixed - the UT tests don't work on the original gundo project for me, and they don't work on this one either. I'll see if I can track that down as well.

**Comment by dsummersl** [comment]
Git bisected from the point where it last worked:

```
# last working point:
git bisect start
git bisect bad
git bisect good 65da6e46fd0dba48954a1d9463fd0d58d9d61319

...
...
...

d7d01c3ef4e3e8192090d4a29e132d3931359257 is the first bad commit
commit d7d01c3ef4e3e8192090d4a29e132d3931359257
Author: xaizek <xaizek@gmail.com>
Date:   Mon Jun 27 23:59:53 2011 +0300

    Move all python code to a separate file.

:040000 040000 12f323423770b1bfeb8073cdf2f249115c8adb2b 754525e6018b5095a2d1e143f6e60dee1018ff73 M      plugin
```

**Comment by dsummersl** [comment]
I'll also add some CI support for this if I can - clearly this has been broken for five years b/c no-one runs these tests.

**Comment by simnalamburt** [comment]
Thanks for the note and the suggestion!
