### ISSUE TITLE
The vim-airline status bar moves to the Mundo pane when opened

### ISSUE THREAD

**Issue by bpierre** [simnalamburt/vim-mundo#39]
Not sure if the problem comes from [vim-airline](https://github.com/vim-airline/vim-airline), Mundo, or both.

When I toggle Mundo, my vim-airline status bar is moved inside of the Mundo tree.

Before opening Mundo (the grey bar at the bottom is tmux, do not pay attention to it):

<img width="1440" alt="screen shot 2016-08-22 at 14 36 08" src="https://cloud.githubusercontent.com/assets/36158/17857451/b0a3e272-6879-11e6-8a49-c76433d73daa.png">

After opening Mundo (with `g:mundo_preview_bottom = 1`):

<img width="1440" alt="screen shot 2016-08-22 at 14 36 15" src="https://cloud.githubusercontent.com/assets/36158/17857456/b2e3cd18-6879-11e6-80db-835b34d47955.png">

**Comment by dsummersl** [comment]
I believe that is the standard behavior for airline: whichever window has cursor focus also contains the airline status bar. Other plugins add 'airline support' - showing a custom airline status bar when focused (say # total undos, mundo settings, etc).

**Comment by bpierre** [comment]
You are right, thanks. I wonder if vim-airline allow to stay on the latest active window if a certain condition is met…

**Comment by dsummersl** [comment]
Yeah that would be nice...I'll check out some other airline compatible plugins and see what they do.
