### ISSUE TITLE
vim-airline integration

### ISSUE THREAD

**Issue by bpierre** [simnalamburt/vim-mundo#40]
Should Mundo be added to the vim-airline integrations?

What kind of information would be the most interesting to have?

See @dsummersl comment here: https://github.com/simnalamburt/vim-mundo/issues/39#issuecomment-241439638

Gundo integration in vim-airline: https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/extensions.vim#L24

**Comment by bpierre** [comment]
Looks like the best way to integrate a plugin with vim-airline https://github.com/vim-airline/vim-airline/blob/d00f7b35d2e615ce7a120214e4615912fc09e630/doc/airline.txt#L868

**Comment by dsummersl** [comment]
I really like this idea. We don't need anything particularly complicated. I think even a simple branded status line (just 'MUNDO') would be less confusing than displaying the user's default airline status line.

**Comment by dsummersl** [comment]
If anybody has a chance to review this before I merge it in, that'd be great. It only provides simple airline statusbars so you are aware that the window you are in is a Mundo window. It leaves the main history window labelled as 'mundo' even when it doesn't have focus to unsure the user knows what the windows are for.

**Comment by dsummersl** [comment]
issue-40 merged.
