### ISSUE TITLE
Tag 3.0.1 release?

### ISSUE THREAD

**Issue by idbrii** [simnalamburt/vim-mundo#41]
v3.0.0 is the most recent tagged release but it contains #30. That looks really bad to new users switching from gundo since checking the help is one of the first things they'll do. It was the first thing I did and I immediately ditched mundo thinking it was an experimental fork. It wasn't until I considered reporting the issue that I found it was already fixed.

Could 67ab896 (the fixing commit) get tagged as v3.0.1? The only additional change is 404a8e8 which is another namechange doc update.

(I'm glad I stuck around: the diff searching is awesome!)

**Comment by dsummersl** [comment]
@idbrii thanks so much for the feedback. Tagged!
