### ISSUE TITLE
Readme says not diverging from upstream

### ISSUE THREAD

**Issue by idbrii** [simnalamburt/vim-mundo#43]
The Readme says:

> #### Do you have any plan to diverge from [upstream][]?
> *   Not yet. It'll always be downstream of original

But #15 made massive changes to the code to rebrand and this plugin is no longer "forked from sjl/vim-gundo" on github. Should that readme segment be removed?

[upstream]: https://github.com/sjl/gundo.vim

**Comment by simnalamburt** [comment]
You're right. vim-mundo is already a lot different from gundo.vim. I'll delete that line
