### ISSUE TITLE
Undefined function: get_padding_line

### ISSUE THREAD

**Issue by dsummersl** [simnalamburt/vim-mundo#45]
While debugging #44 I found a function that is not defined in the codebase. I followed the git history and it looks like when the original author imported the mercurial graph implementation he didn't import that function. It must be a fairly rare that `get_padding_line()` is called because I don't think anyone has complained about it. I suggest we remove it.

https://github.com/simnalamburt/vim-mundo/blob/master/autoload/mundo/graphlog.py#L150

**Comment by simnalamburt** [comment]
Wow it is amazing that I noticed it two years after we made vim-mundo. We definitely should do some refactoring when we have some spare time. lol
