### ISSUE TITLE
"g:mundo_inline_graph" should be "g:mundo_inline_undo" in the doc

### ISSUE THREAD

**Issue by xeyownt** [simnalamburt/vim-mundo#48]
In the doc, title for section 3.14 is `g:mundo_inline_graph`.
It should be `g:mundo_inline_undo`.

Or vice-versa.

Thanks for the nice plugin btw.

**Comment by dsummersl** [comment]
Oops! Thanks so much for pointing that out. We'll get it fixed shortly.
