### ISSUE TITLE
Error if you press 'j' in Gundo graph pane

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/vim-mundo#5]
Error Reproduction
--------
1.  Place cursor at the bottom of the gundo pane like below:

    ![](http://i.imgur.com/6qbMgev.png)

2.  Press `j`

3.  You'll get below:

    ![](http://i.imgur.com/p2Md0OL.png)

    ```
    Error detected while processing function <SNR>125_GundoPython:
    line    4:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/HyeonKim/.dotfiles/.vim/plugged/vim-mundo/autoload/gundo.py", line 777, in GundoMove
        minidx = min(idxs)
    ValueError: min() arg is an empty sequence
    ```

Cause
--------
`generate` function makes trailing empty line

```python
[
    ['@ ', '[1] <1 min ago +\\n\\n+'],
    ['| ', ''],
    ['o ', '[0] Original   '],
    ['  ', '']
]
```

Solutions
--------
1. Don't let `ascii` function make empty line
2. Don't let `generate` function make empty line
3. Don't let `GundoRenderGraph` function render empty line

**Comment by dsummersl** [comment]
ah, good catch! Any of those fixes you suggest would do; I think I prefer the first one.

Something like this?

https://gist.github.com/dsummersl/579749d69eed412ec1b5

**Comment by dsummersl** [comment]
also notice i left an `echom` - I'll commit a fix to take that out and this gist change above if it looks okay to youl.

**Comment by dsummersl** [comment]
oh - hah - you already did it!
