### ISSUE TITLE
Colors dissapear when sourcing .vimrc after plugin load

### ISSUE THREAD

**Issue by ruohola** [simnalamburt/vim-mundo#70]
Steps:

1. Open file
2. Open Mundo
  \- colors show up correctly
3. Close Mundo
4. :so $MYVIMRC
5. Open Mundo
  \- Mundo is black and white

**Comment by ruohola** [comment]
fixed this by changing a section in my vimrc
from this:
`syntax enable`
to this:
`if !exists("g:syntax_on")
    syntax enable
endif`

**Comment by simnalamburt** [comment]
This issue has been fixed by https://github.com/simnalamburt/vim-mundo/pull/74
