### ISSUE TITLE
Preview button (r) not remappable

### ISSUE THREAD

**Issue by runiq** [simnalamburt/vim-mundo#72]
Hey,

thanks for taking up Gundo and making it better! :)

I have a little problem due to my [keyboard layout](https://adnw.de), which uses `t` and `r` in place of `j` and `k`. Unfortunately `r` is mapped to rendering previews and not remappable.

Could you expose a setting for changing the keybinding, please?

Thanks again! :)

**Comment by dsummersl** [comment]
oh, woops - yes, I'll try and get that out for you soon.

**Comment by dsummersl** [comment]
I started this last night and its turned into a little bigger thing (general ability to configure all mappings rather than the piecemeal thing we have in place now)...I hope to have this finished up this weekend.

**Comment by dsummersl** [comment]
@runiq I'ved added a PR that allows you to remap your mundo keys as you see fit. Give it a try when you get a chance.

**Comment by runiq** [comment]
Hi! Sorry for not getting to this sooner. Everything appears to be working great! Thanks for all your work! :)
