### ISSUE TITLE
Python fatal error toggling on Mundo

### ISSUE THREAD

**Issue by cridemichel** [simnalamburt/vim-mundo#83]
Dear All,
first of all thank you very much for this very useful and well done vim plugin.
I am using macvim (VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 11 2019 08:22:43)
macOS version Included patches: 1-1517) and, on toggling on Mundo, I frequently stumble upon the following python error:

Error detected while processing function mundo#MundoToggle[1]..<SNR>117_MundoToggle[4]..<SNR>117_MundoOpen[40]..<SNR>117_MundoP
ython:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/demichel/.vim/bundle/vim-mundo/autoload/mundo.py", line 284, in MundoMove
    minidx = min(idxs)
ValueError: min() arg is an empty sequence

which can be easily be fixed by replacing 

minidx=min(idxs)

with:

if len(idxs)==0:
    minidx=0
else:
    minidx=min(idxs)

even though I am not 100% sure it is the right way of fixing it.
By diffing against original (not fixed) version on has:
--- mundo.py	2019-07-27 11:06:43.000000000 +0200
+++ mundo_fixed.py	2019-07-27 11:01:37.000000000 +0200
@@ -281,7 +281,10 @@
         idxs.append(idx2)
     if idx3 != -1:
         idxs.append(idx3)
\-    minidx = min(idxs)
\+    if len(idxs)==0:
\+        minidx=0
\+    else:
\+        minidx = min(idxs)
     if idx1 == minidx:
         vim.command("call cursor(0, %d + 1)" % idx1)
     elif idx2 == minidx:

best regards,
Cristiano

**Comment by simnalamburt** [comment]
Closed by https://github.com/simnalamburt/vim-mundo/pull/89
