### ISSUE TITLE
Doesnt work if also have animate and lens plugins

### ISSUE THREAD

**Issue by thepenguinthatwants** [simnalamburt/vim-mundo#94]
Hi!
For some reasons with these plugins

```
Plug 'camspiers/animate.vim'
Plug 'camspiers/lens.vim'
```

mundo cant choose other objects and it just when pressing j it randomly jumps into other buffers.

**Comment by simnalamburt** [comment]
Thank you for the report and I successfully reproduced the problem.

Well... I don't know the detail of implementation of animate.vim and lens.vim. But this is my theory.

- Animate.vim and Lens.vim want to resize "current" buffer
- Everytime you type <kbd>j</kbd> key in Mundo, it updates editor buffer, mundo preview buffer, and mundo buffer simultaneously. Well, it changes what "current" buffer is quite a lot.
- But animate.vim and lens.vim have no idea that "current" buffer has been changed by other plugins. So they randomly change the buffers size and focus.

If this theory is correct, I believe this is an issue of animate.vim or lens.vim, not vim-mundo. How do you think?

**Comment by thepenguinthatwants** [comment]
Yeah you are right! Its certainly not a problem of this plugin. Mundo has always being very nice plugin.

Its just that I was suprised for it to affect mundo.

**Comment by simnalamburt** [comment]
@thepenguinthatwants Well this is just a theory, and there is a chance that Mundo actually has a problem. 😅 I don't know how to do it yet but maybe vim-mundo can workaround this problem without changing animate.vim or lens.vim

Please let me know if it there is an actual issue of vim-mundo, or if you find out how to workaround this problem. Thanks!

**Comment by pkfm** [comment]
you can disable `lens.vim` for specific filetypes, namely `Mundo` and `MundoDiff`, with the
`g:lens#disabled_filetypes` options. i.e.

```
let g:lens#disabled_filetypes = ['Mundo', 'MundoDiff']
```

you can determine a buffer's filetype with the command `:set ft?`.

it seems there was a problem with `lens.vim` and `animate.vim` after all and setting this option does not functin as expected unless `animate.vim` is disabled. see [issue #12](https://github.com/camspiers/lens.vim/issues/12) from `lens.vim`. you can resolve the issue by plugging a [fork](https://github.com/ipod825/lens.vim) by [ipod825](https://github.com/ipod825/lens.vim), who has also implemented a seperate resizing [plugin](https://github.com/ipod825/war.vim) based on user defined rules. you might also apply the [diff](https://github.com/ipod825/lens.vim/commit/8ff16376980824f76a3a5503c31e341f078455c4) manually as it just a few lines.
<F12>
`lens.vim` also supplies an option to disable the plugin, as well as a toggling function which may also be of interest.

```
let g:lens#disabled = 1
function! lens#toggle() abort
```
