### ISSUE TITLE
Other options to revert contents of change?

### ISSUE THREAD

**Issue by thepenguinthatwants** [simnalamburt/vim-mundo#95]
Pressing return on a state (or double clicking on it) will revert the contents of the file to match that state. 

Seems like I've mapped return on something else as this doesnt work. Does double click mean clicking by mouse? Is there any way to map revert content to U or something?

**Comment by simnalamburt** [comment]
@thepenguinthatwants You can change the Mundo keymap with `g:mundo_mappings` option. :) Thank you for using Mundo!

https://github.com/simnalamburt/vim-mundo/blob/046fc0664b953ab17153da379df0b9fd34b85ec1/doc/mundo.txt#L192-L209

**Comment by thepenguinthatwants** [comment]
let g:mundo_mappings = {
           \ '<CR>': 'preview',
           \ 'o': 'preview',
           \ 'j': 'move_older',
 }

When I added this line on my vimrc I've got

```
E723: Missing end of Dictionary '}':
E15: Invalid expression: { '<CR>': 'preview', 'o': 'preview', 'j': 'move_older',
line    9:
E492: Not an editor command:  }
line    8:
E723: Missing end of Dictionary '}':
E15: Invalid expression: { '<CR>': 'preview', 'o': 'preview', 'j': 'move_older',
line    9:
E492: Not an editor command:  }
```

**Comment by simnalamburt** [comment]
@thepenguinthatwants Remove the trailing comma like this:

```vim
let g:mundo_mappings = {
  \ '': 'preview',
  \ 'o': 'preview',
  \ 'j': 'move_older'}
```

I tried it and it works perfect!
